name: CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: jethrodaniel/setup-zig@fix-caching
        with:
          version: 0.12.0-dev.3480+9dac8db2d

      - run: zig version
      - run: zig env

      - name: Build
        run: zig build release

      - uses: actions/upload-artifact@v4
        with:
          name: release
          path: zig-out/release
