name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: jethrodaniel/setup-zig@fix-caching
        with:
          version: 0.12.0-dev.3480+9dac8db2d
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Install qemu
        run: sudo apt-get update && sudo apt-get install -y qemu-user-static

      - run: zig version
      - run: zig env

      - name: Build
        run: zig build release

      - name: Add zig-out to PATH
        run: Add-Content $env:GITHUB_PATH "$env:GITHUB_WORKSPACE\zig-out\bin"


      - uses: actions/upload-artifact@v4
        with:
          name: bin
          path: zig-out/bin
